In [1]:
import pandas as pd 
import os

In [2]:
cancer_name = "ACC"  # 癌症名称
indicator = 'RNA_Seq' # 指标

In [3]:
path = os.path.join("..", "dataset", cancer_name, indicator)
df = pd.read_csv(path, sep="\t", index_col=0).T

In [4]:
df.isna().sum().sum()

np.int64(0)

In [8]:
(df == 0).sum(axis=1)

TCGA-OR-A5LC-01    4094
TCGA-OR-A5JJ-01    3065
TCGA-OR-A5K3-01    4190
TCGA-PK-A5HA-01    3781
TCGA-OR-A5LN-01    4227
                   ...
TCGA-OR-A5KX-01    3776
TCGA-OR-A5L5-01    3173
TCGA-P6-A5OG-01    3346
TCGA-OR-A5LR-01    3783
TCGA-OR-A5LT-01    3993
Length: 79, dtype: int64

In [4]:
df.head() # 查看前五行

,0,1,2,3,4,5,6,7,8,9,...,20520,20521,20522,20523,20524,20525,20526,20527,20528,20529
sample,ARHGEF10L,HIF3A,RNF17,RNF10,RNF11,RNF13,GTF2IP1,REM1,MTVR2,RTN4RL2,...,TULP2,NPY5R,GNGT2,GNGT1,TULP3,PTRF,BCL6B,GSTK1,SELP,SELS
TCGA-OR-A5LC-01,6.2537,4.7431,0.0,12.3405,10.2326,9.9114,12.6294,4.8144,0.7471,4.1668,...,0.0,1.2369,4.2718,0.0,9.4082,12.1791,8.1493,12.3512,2.1349,11.1654
TCGA-OR-A5JJ-01,8.6468,4.4576,0.0,12.1763,10.2696,9.9354,12.6974,4.2702,0.5323,3.4936,...,0.0,2.5628,2.0439,0.5323,9.653,11.0509,7.5406,12.6932,2.1921,12.0223
TCGA-OR-A5K3-01,8.0773,5.2181,0.0,13.4269,10.4399,10.448,12.6752,1.8429,0.0,2.9008,...,0.0,0.0,3.3299,0.0,8.8941,11.3881,6.4961,13.463,2.9008,10.172
TCGA-PK-A5HA-01,8.5349,2.4357,0.0,12.3032,10.3281,10.4491,12.6055,5.0432,0.0,5.0907,...,0.6335,0.0,4.456,0.0,8.8769,11.2305,8.4327,12.1661,5.4951,9.4352

In [5]:
df.tail() # 查看后五行

,0,1,2,3,4,5,6,7,8,9,...,20520,20521,20522,20523,20524,20525,20526,20527,20528,20529
TCGA-OR-A5KX-01,7.5684,4.3306,0.0,13.0964,10.7704,10.7748,13.0629,0.5636,0.0,4.5525,...,0.0,0.0,2.8508,0.5636,8.4956,12.8579,8.1998,10.0567,3.4006,10.5672
TCGA-OR-A5L5-01,9.1999,10.419,0.0,12.8204,10.8607,10.8256,12.3124,5.0541,0.0,2.2699,...,0.6286,6.2855,4.5139,0.0,9.1892,12.4787,7.5943,11.7898,7.6345,10.4173
TCGA-P6-A5OG-01,8.1566,4.7082,0.0,11.4329,10.0367,9.5136,11.3778,5.7165,0.0,6.0064,...,0.0,0.0,6.0258,0.9006,8.899,14.2299,10.8652,11.372,5.7165,9.9963
TCGA-OR-A5LR-01,8.2155,11.1912,0.8772,13.4041,10.7793,11.0751,11.9683,5.7697,0.0,2.9438,...,0.0,2.9438,3.9285,0.0,9.5571,13.1398,7.8733,11.3683,5.7247,9.9441
TCGA-OR-A5LT-01,9.9746,2.3928,0.8878,12.106,11.1116,11.132,11.7788,1.8282,0.0,5.058,...,0.0,0.8878,1.4333,0.0,9.3458,10.7102,4.9824,10.708,0.0,10.0632

In [6]:
df.sample(5) # 随机查看5行

,0,1,2,3,4,5,6,7,8,9,...,20520,20521,20522,20523,20524,20525,20526,20527,20528,20529
TCGA-OR-A5LN-01,8.9196,5.8492,0.0,12.4274,10.4852,11.0181,13.12,2.4917,0.0,3.1847,...,0.0,2.1597,4.5214,0.0,9.485,12.4978,8.526,12.4398,1.7277,10.6716
TCGA-OR-A5KT-01,9.1509,7.5163,0.0,11.8015,10.8931,10.2827,12.1124,6.1169,0.0,3.6508,...,0.0,0.0,5.3051,0.0,8.681,12.3648,9.6345,11.3923,3.4106,11.5113
TCGA-OR-A5J1-01,9.2229,5.2289,0.0,13.044,11.3233,10.5275,12.7366,4.5883,0.0,1.5466,...,0.5659,0.9713,4.1931,4.3025,8.2998,10.5737,6.4584,12.2517,3.34,11.173
TCGA-OR-A5JL-01,8.7976,5.4357,0.0,12.4818,11.3479,11.0256,13.046,2.5105,0.0,3.2413,...,1.5257,2.5105,3.378,0.0,8.4803,9.9499,8.2525,12.7387,3.6719,12.0809
TCGA-OU-A5PI-01,8.8842,1.4385,0.6509,12.5146,10.8403,11.2807,12.6464,4.3085,0.0,3.167,...,0.0,4.3085,2.3193,0.0,10.1657,11.1402,6.5359,12.0289,4.9642,10.314

In [7]:
df.shape # 查看表格行列数

(80, 20530)

In [8]:
df.columns # 查看列名

RangeIndex(start=0, stop=20530, step=1)

In [9]:
df.info() # 查看信息 缺失等

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, sample to TCGA-OR-A5LT-01
Columns: 20530 entries, 0 to 20529
dtypes: object(20530)
memory usage: 12.5+ MB

In [10]:
df.describe() # 列出列的统计信息

,0,1,2,3,4,5,6,7,8,9,...,20520,20521,20522,20523,20524,20525,20526,20527,20528,20529
count,80,80,80.0,80.0000,80,80,80.0000,80,80.0,80.0,...,80.0,80.0,80,80.0,80,80,80,80,80.0,80
unique,80,80,19.0,79.0000,80,80,79.0000,80,13.0,79.0,...,26.0,61.0,80,25.0,80,80,80,80,72.0,80
top,ARHGEF10L,HIF3A,0.0,12.4274,RNF11,RNF13,13.0629,REM1,0.0,0.0,...,0.0,0.0,GNGT2,0.0,TULP3,PTRF,BCL6B,GSTK1,0.0,SELS
freq,1,1,62.0,2.0000,1,1,2.0000,1,68.0,2.0,...,55.0,19.0,1,56.0,1,1,1,1,9.0,1

In [8]:
# progCAE的样例数据
cancer_name = "data"  # 癌症名称
indicator = "example_RNA.csv"  # 指标
path = os.path.join("..", "dataset", cancer_name, indicator)
df2 = pd.read_csv(path).T

In [9]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,601,602,603,604,605,606,607,608,609,610
Unnamed: 0,TCGA-E9-A228-01,TCGA-D8-A1J8-01,TCGA-AC-A3YI-01,TCGA-OL-A66J-01,TCGA-EW-A1IX-01,TCGA-B6-A1KF-01,TCGA-C8-A1HO-01,TCGA-BH-A1F5-01,TCGA-XX-A89A-01,TCGA-D8-A27K-01,...,TCGA-BH-A0BT-01,TCGA-EW-A1PE-01,TCGA-OL-A5RX-01,TCGA-E2-A1AZ-01,TCGA-AC-A8OR-01,TCGA-MS-A51U-01,TCGA-EW-A1IY-01,TCGA-BH-A1FN-01,TCGA-E2-A3DX-01,TCGA-E9-A1RF-01
SCARNA18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
KATNB1,9.2597,7.3008,8.1821,8.2831,8.6874,9.247,8.7607,5.8879,8.6221,7.6898,...,7.876,8.2386,8.6068,8.469,9.0381,8.6849,6.6486,7.8241,8.4004,8.5326
PNKP,9.6741,7.5467,9.065,9.8946,9.0494,7.3101,8.1316,6.7381,9.587,8.3587,...,9.7806,9.1024,9.6695,7.9791,9.5668,10.1611,7.2151,7.9878,9.1913,10.4843
MGAM,5.9222,8.7498,5.516,4.7135,5.2335,0.5592,2.4923,3.718,4.6217,3.14,...,2.0242,4.3272,3.6548,1.3222,4.6273,2.5096,2.8496,2.6664,7.453,2.6135

In [10]:
df2.shape

(10001, 611)