In [1]:
import pandas as pd 
import os

In [2]:
cancer_name = "ACC"  # 癌症名称
indicator = 'DNA_methylation' # 指标

In [3]:
path = os.path.join("..", "dataset", cancer_name, indicator)
df = pd.read_csv(path, sep="\t").T

In [4]:
df.head() # 查看前五行

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
sample,cg13332474,cg00651829,cg17027195,cg09868354,cg03050183,cg01989731,cg06819656,cg04244851,cg19669385,cg04244855,...,cg14483317,cg05534403,cg04487158,cg00810133,cg11692435,cg16018548,cg10230711,cg16651827,cg18138552,cg07883722
TCGA-OR-A5LM-01,0.0218,0.0363,0.0423,0.1117,0.1197,NaN,0.6836,0.9366,0.9563,0.9418,...,0.1295,NaN,NaN,NaN,0.9852,NaN,0.0512,0.7356,0.0371,0.7713
TCGA-OR-A5K1-01,0.0289,0.0199,0.0352,0.0774,0.0653,NaN,0.8838,0.9256,0.9174,0.8689,...,0.0291,NaN,NaN,NaN,0.9791,NaN,0.0401,0.7414,0.0227,0.9165
TCGA-OR-A5K2-01,0.5992,0.027,0.0576,0.0885,0.0862,NaN,0.8545,0.942,0.9556,0.9426,...,0.0592,NaN,NaN,NaN,0.9562,NaN,0.0978,0.8319,0.042,0.9356
TCGA-OR-A5JM-01,0.0307,0.0205,0.0436,0.1201,0.0522,NaN,0.8409,0.9279,0.9622,0.8687,...,0.0333,NaN,NaN,NaN,0.9871,NaN,0.0542,0.7457,0.0256,0.9367

In [5]:
df.tail() # 查看后五行

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
TCGA-OR-A5J8-01,0.0548,0.1734,0.0361,0.071,0.1382,NaN,0.902,0.9369,0.9646,0.7835,...,0.1813,NaN,NaN,NaN,0.9723,NaN,0.0478,0.5584,0.0265,0.9458
TCGA-OR-A5JX-01,0.0243,0.03,0.0357,0.0511,0.0645,NaN,0.7732,0.944,0.9651,0.9366,...,0.0432,NaN,NaN,NaN,0.9868,NaN,0.0565,0.7944,0.0234,0.918
TCGA-OR-A5JC-01,0.0363,0.0598,0.0647,0.0731,0.0398,NaN,0.7866,0.9255,0.8971,0.9273,...,0.0571,NaN,NaN,NaN,0.9399,NaN,0.0959,0.7423,0.034,0.9449
TCGA-OR-A5KZ-01,0.0239,0.0274,0.0467,0.0935,0.0634,NaN,0.8512,0.863,0.9591,0.7456,...,0.0377,NaN,NaN,NaN,0.9856,NaN,0.0914,0.7055,0.0301,0.535
TCGA-OR-A5JE-01,0.3721,0.6388,0.0472,0.0902,0.612,NaN,0.8634,0.9233,0.9531,0.9413,...,0.059,NaN,NaN,NaN,0.988,NaN,0.0947,0.7591,0.0309,0.9565

In [6]:
df.sample(5) # 随机查看5行

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
TCGA-OR-A5J3-01,0.0212,0.0241,0.0364,0.1015,0.0789,NaN,0.8351,0.9333,0.9634,0.9418,...,0.0325,NaN,NaN,NaN,0.8367,NaN,0.1625,0.7541,0.0294,0.9469
TCGA-OR-A5JZ-01,0.0317,0.0244,0.0678,0.1086,0.0739,NaN,0.7355,0.9316,0.9616,0.9425,...,0.0416,NaN,NaN,NaN,0.9877,NaN,0.0623,0.7605,0.0374,0.2852
TCGA-P6-A5OG-01,0.168,0.0401,0.0509,0.0669,0.092,NaN,0.8951,0.9081,0.9598,0.9419,...,0.0544,NaN,NaN,NaN,0.9872,NaN,0.0542,0.7149,0.035,0.9589
TCGA-OR-A5KO-01,0.0239,0.0193,0.0323,0.1035,0.4392,NaN,0.8599,0.9501,0.9606,0.9499,...,0.0719,NaN,NaN,NaN,0.9883,NaN,0.0545,0.7696,0.0292,0.9504
TCGA-OR-A5L3-01,0.0276,0.018,0.0352,0.0711,0.0822,NaN,0.8567,0.942,0.9458,0.6378,...,0.0282,NaN,NaN,NaN,0.8643,NaN,0.0466,0.691,0.0315,0.8956

In [7]:
df.shape # 查看表格行列数

(81, 485577)

In [8]:
df.columns # 查看列名

RangeIndex(start=0, stop=485577, step=1)

In [9]:
df.info() # 查看信息 缺失等

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, sample to TCGA-OR-A5JE-01
Columns: 485577 entries, 0 to 485576
dtypes: object(485577)
memory usage: 300.1+ MB

In [10]:
df.describe() # 列出列的统计信息

KeyboardInterrupt:

In [ ]:
# progCAE的样例数据
cancer_name = "data"  # 癌症名称
indicator = "example_Meth.csv"  # 指标
path = os.path.join("..", "dataset", cancer_name, indicator)
df2 = pd.read_csv(path).T

In [ ]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,601,602,603,604,605,606,607,608,609,610
Unnamed: 0,TCGA-E9-A228-01,TCGA-D8-A1J8-01,TCGA-AC-A3YI-01,TCGA-OL-A66J-01,TCGA-EW-A1IX-01,TCGA-B6-A1KF-01,TCGA-C8-A1HO-01,TCGA-BH-A1F5-01,TCGA-XX-A89A-01,TCGA-D8-A27K-01,...,TCGA-BH-A0BT-01,TCGA-EW-A1PE-01,TCGA-OL-A5RX-01,TCGA-E2-A1AZ-01,TCGA-AC-A8OR-01,TCGA-MS-A51U-01,TCGA-EW-A1IY-01,TCGA-BH-A1FN-01,TCGA-E2-A3DX-01,TCGA-E9-A1RF-01
cg14577840,0.9047,0.9151,0.8807,0.9253,0.8981,0.9194,0.9114,0.902,0.8699,0.8987,...,0.833,0.9294,0.9111,0.9124,0.802,0.8691,0.8803,0.8872,0.8807,0.9234
cg14196011,0.9618,0.9211,0.8791,0.9248,0.9219,0.9209,0.937,0.9285,0.8473,0.9074,...,0.8814,0.9286,0.8979,0.9231,0.8292,0.8439,0.9315,0.9215,0.9195,0.9261
cg09238520,0.9399,0.9359,0.8901,0.9259,0.9351,0.9378,0.9393,0.921,0.8744,0.9264,...,0.8825,0.9458,0.8921,0.9312,0.8376,0.8581,0.9248,0.9312,0.9087,0.9291
cg27345735,0.2812,0.2311,0.1892,0.2174,0.2073,0.242,0.1949,0.3482,0.207,0.2411,...,0.2492,0.2223,0.1642,0.3479,0.1807,0.1532,0.2185,0.3334,0.1994,0.3463

In [ ]:
df2.shape

(3001, 611)